/*
 * freeRADIUS Admin - OpenAPI 3.0
 *
 * get http api for admin freeradius
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package http

type User struct {

	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`
}
