/*
 * freeRADIUS Admin - OpenAPI 3.0
 *
 * get http api for admin freeradius
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package http

import (
	"net/http"
	"strings"
	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

var routes = Routes{

	Route{
		"AddUser",
		strings.ToUpper("Post"),
		"/addUser",
		AddUser,
	},

	Route{
		"GetAllUser",
		strings.ToUpper("Post"),
		"/getAllUsers",
		GetAllUser,
	},
}
